[en]
languageName = "English"
weight = 1
title = "My blog beats!!!"
slogan = "Blog the beat12"
#[languages.en.params]
#linkedin = "https://linkedin.com/whoever"
[de]
languageName = "German"
weight = 2
title = "Meine Blog beats"