baseurl = "https://blogbeat.github.io"
title = "My blog beats"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
paginate = 5000 #frontpage pagination

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  header_image = "../images/homeflowers.jpg"
  title = "Mind Blog"
  slogan = "Blogs that beat"
  SEOTitle = "Blogbeats Blog"
  keyword = "Blogbeats, Blog , Beats, Mind, Thoughts"

  # Sidebar settings
  sidebar_about_description = "Human, Friend, Soulmate"
  sidebar_avatar = "images/avatar.jpg"
  about_me = true

  featured_tags = true
  featured_condition_size = 2 # How many posts have to have a given tag to be featured (greater-than)

  image_404 = "images/404.jpg"
  title_404 = "We couldn't find what you were looking for..."

  omit_categories = false

  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

  [params.social]
  rss            = true
  email          = "mailblogbeats@gmail.com"
  github         = "https://github.com/blogbeat"
