# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Clean White"
license = "Apache"
licenselink = "tbd"
description = "beatfull"
homepage = "tbd"
tags = [ "minimal", "responsive", "blog","light", "clean", "search"]
features = ["disqus", "site search", "responsive", "google analytics", "side bar"]
min_version = 0.10

[author]
  name = "MM"
  homepage = "tbd"

# If porting an existing theme
[original]
  name = "huxblog"
  homepage = "tbd"
